### ISSUE TITLE
Love this! Thank you.

### ISSUE THREAD

**Issue by canadaduane** [baileyherbert/svelte-webpack-starter#1]
It doesn't look like this project has had as much attention as it deserves--so, THANK YOU for putting out there, and providing nice documentation and options. This is a really nice starter for svelte, webpack, and typescript.

**Comment by baileyherbert** [comment]
Hey mate! Very happy to hear that it was useful to you! I made it for myself not long ago, and didn't really expect anyone to find it. Let me know if you run into any issues. Thank you and stay safe! 😀

**Comment by rafrasenberg** [comment]
Awesome repo man!!! Thanks a lot. Just wanted to show my sincere appreciation.

I used this some time ago but wanted to upgrade to Webpack 5, so I came back to this repo and I see you literally pushed an upgrade 4 days ago. Awesome 😄

**Comment by canadaduane** [comment]
Oh wow, I hadn't noticed! Webpack 5. Gotta check this out.

**Comment by baileyherbert** [comment]
Thanks guys! I'm happy to hear that you're finding it useful. 😄 

I heard Webpack 5 had improved tree shaking, so I couldn't wait to try it out (and to debug config files for a few hours haha!)
