### ISSUE TITLE
Issue with using npm svelte components

### ISSUE THREAD

**Issue by eni9889** [baileyherbert/svelte-webpack-starter#12]
When I use any external svelte components like `@sveltejs/svelte-virtual-list` or `svelte-carousel` I get the error:
```
ERROR in ./node_modules/@sveltejs/svelte-virtual-list/VirtualList.svelte 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <script>
|       import { onMount, tick } from 'svelte';
| 

webpack 5.67.0 compiled with 1 error in 8086 ms

```

If I get rid of the exclude part in 
```
                test: /\.svelte$/,
                exclude: /node_modules/,
```

The build works but the component does not actually work.

**Comment by baileyherbert** [comment]
I was able to get `@sveltejs/svelte-virtual-list` working properly by removing that exclude in bfaed6a5927890b1cc1558691d7c1ece5442a842. You will need to restart the dev server after making this change. Can you confirm?

**Comment by eni9889** [comment]
@baileyherbert it looks like it works the styles were just all wrong. Are you able to get `svelte-carousel` working?

**Comment by baileyherbert** [comment]
I did also get `svelte-carousel` working with the same modification. I can also confirm that the styles from both packages are working for me.
