### ISSUE TITLE
Failed to load '*******/webpack.config.ts' config

### ISSUE THREAD

**Issue by soshiharami** [baileyherbert/svelte-webpack-starter#4]
```
yarn dev
yarn run v1.22.10
$ webpack serve
[webpack-cli] Failed to load '/home/soshi/project/test/webpack.config.ts' config
[webpack-cli] webpack.config.ts:98:10 - error TS2322: Type 'typeof autoprefixer' is not assignable to type 'AcceptedPlugin'.
  Property 'process' is missing in type 'typeof autoprefixer' but required in type 'Plugin<any>'.

98          Autoprefixer
            ~~~~~~~~~~~~

  node_modules/postcss/lib/postcss.d.ts:24:5
    24     process: (css: string | {
           ~~~~~~~
    'process' is declared here.

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
 ```
Hello, I am a Japanese student engineers.
 When I downloaded this template and tried to start development, I got an error in webpack.
 It looks like a postcss error.
 
Sorry for my poor English

**Comment by baileyherbert** [comment]
Strange! The error is only occurring when I install with `yarn`. It works fine with `npm` or `pnpm`. I'll have to investigate further, but it's something to do with type definitions.

As a temporary fix, try adding `<any>` before `Autoprefixer` on line 98 of webpack.config.ts:

```ts
plugins: [
	<any>Autoprefixer
]
```

**Comment by soshiharami** [comment]
Thank you for your quick response!
Thanks for the great template
